# nacos注册中心配置最好放在bootstrap.yml中，因为配置中心只能在那里配置
#spring:
#  application:
#    name: server-user
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848 # nacos\u5730\u5740
#        username: nacos
#        password: nacos
#
#    sentinel:
#      transport:
#        dashboard: 127.0.0.1:8858

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
#    username: root
#    password: admin
#    hikari:
#      minimum-idle: 10
#      maximum-pool-size: 20
#      idle-timeout: 500000
#      max-lifetime: 540000
#      connection-timeout: 60000
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#
##: ============== mybatis-plus ===============
#mybatis-plus:
#  type-aliases-package: com.example.springcloudnacosuser.module.user.entity
#  mapper-locations: mapper/**.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: deletedFlag
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#
#
#feign:
#  #替换掉JDK默认HttpURLConnection实现的 Http Client
#  httpclient:
#    enabled: true
#  sentinel:
#    enable: true
#  client:
#    config:
#      default:
#        #连接超时时间
#        connectTimeout: 5000
#        #读取超时时间
#        readTimeout: 5000