//当前规则文件用于测试date-effective属性
package testdateeffective
import java.text.SimpleDateFormat
import java.util.Date
import com.example.drools.order.entity.DateEntity

rule "rule_dateeffective_1"
//    date-effective "2021-8-17 18:10" //date-effective属性用于指定当前规则生效时间

    //一月JAN、二月FEB、三月MAR、四月APR、五月MAY、六月JUN、
    //七月JUL、八月AUG、九月SEPT、十月OCT、十一月NOV、十二月DEC。
    date-effective "10-JAN-2020"
    when
        DateEntity(open==1)
    then
        System.out.println("规则：rule_dateeffective_1触发了，触发的时间为：" + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()));
end