package testhalt
import com.example.drools.order.entity.Student5

rule "rule_halt_1"
    when
        Student5(age>10)
    then
        System.out.println("规则：rule_halt_1触发");
        drools.halt();//立即终止后面所有规则执行
        System.out.println("本rule halt后的脚本依然会执行");
        //返回工作内存对象
        System.out.println("工作内存对象:"+drools.getWorkingMemory());
        //返回规则对象
        System.out.println("规则对象:"+drools.getRule());
end

//当前规则并不会触发，因为上面的规则调用了halt方法导致后面所有规则都不会执行
rule "rule_halt_2"
    when
        Student5(age>15)
    then
        System.out.println("规则：rule_halt_2触发");
end